trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo "Checking project files"
    ls -la
    echo "Checking SQL file"
    cat sql/transaction_report.sql
  displayName: "Validate Source"

- script: |
    docker build -t banking-app:$(Build.BuildId) .
  displayName: "Build Docker Image"

- script: |
    docker images
  displayName: "Verify Docker Image"
